server:
  port: 8080

spring:
  application:
    name: smart-clinic-management-system

  datasource:
    url: jdbc:mysql://mysql:3306/cms?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: clinic_user
    password: clinic_pass
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

  mongodb:
    uri: mongodb://clinic_user:clinic_pass@mongodb:27017/cms?authSource=admin
    auto-index-creation: true

management:
  health:
    db:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health


logging:
  level:
    root: INFO
    com.rungrukuk: DEBUG