name: Lint Dockerfiles

on:
  push:
  pull_request:

jobs:
  dockerlint:
    runs-on: ubuntu-latest
    name: Lint Dockerfiles

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./Dockerfile
